### ISSUE TITLE
When a collab is entered that already has data/roles, display them

### ISSUE THREAD

**Issue by eberleant** [Youtaite-Network/youtaite-network-client#51]
This allows existing collabs to be edited

### Related
- [x] Blocked by youtaite-network/youtaite-network-api#33
- [x] Blocked by youtaite-network/youtaite-network-api#34
- [ ] Blocked by youtaite-network/youtaite-network-api#54
