### ISSUE TITLE
Allow searching for any collabs with 1+ roles on home page

### ISSUE THREAD

**Issue by eberleant** [Youtaite-Network/youtaite-network-client#58]
Allow searching for any collabs with 1+ roles on home page, even if they have no connections to an existing collab. This is nice for new users who enter a collab that doesn't (initially) have any connections. They should be able to find the collab on the network even if it's isolated, to encourage them to enter more.

### Related
- [ ] Blocked by youtaite-network/youtaite-network-api#29

### Tasks
- [ ] On home page, filter the collabs endpoint to only get collabs with roles
- [ ] Users can search for collabs with no connections to any other collab in the network
- [ ] Before and after staging, measure network performance. Add observations as a comment.
